# Generated by Django 6.0.3 on 2026-03-06 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(blank=True, help_text='Auto-generated owner ID', max_length=10, unique=True, verbose_name='Owner ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Owner Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner_id'], name='go_data_own_owner_i_8bbb5f_idx'), models.Index(fields=['name'], name='go_data_own_name_43d1b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='e.g., AP1, B1, B2, C1', max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, help_text='e.g., Category AP1, Category B1', max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='go_data_veh_code_9359e7_idx'), models.Index(fields=['is_active'], name='go_data_veh_is_acti_fc3f7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='e.g., COM, PRV, NGO, DIP', max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='e.g., Commercial, Private, NGO, Diplomatic', max_length=50, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vehicle type is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='go_data_veh_code_0a626e_idx'), models.Index(fields=['is_active'], name='go_data_veh_is_acti_fd27d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, db_index=True, help_text='5-character code (auto-generated)', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5), django.core.validators.RegexValidator(code='invalid_vin', message='VIN must be 5 characters: letters (excluding I,O,Q) and numbers', regex='^[A-HJ-NPR-Z0-9]{5}$')], verbose_name='VIN')),
                ('vehicle_reg', models.CharField(blank=True, db_index=True, help_text='e.g., ABC 200', max_length=20, verbose_name='Vehicle Registration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vehicle registration is active', verbose_name='Active')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Format: MM/YYYY', null=True, verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('owner', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='go_data.owner', verbose_name='Owner')),
                ('category', models.ForeignKey(blank=True, help_text='e.g., AP1, B1, B2', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='go_data.vehiclecategory', verbose_name='Vehicle Category')),
                ('vehicle_type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='go_data.vehicletype', verbose_name='Vehicle Type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
                'permissions': [('can_print_vehicle_card', 'Can print vehicle card'), ('can_renew_vehicle', 'Can renew vehicle registration')],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printed_by', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='go_data.vehicle')),
            ],
            options={
                'verbose_name': 'Print Log',
                'verbose_name_plural': 'Print Logs',
                'ordering': ['-printed_at'],
                'indexes': [models.Index(fields=['printed_at'], name='go_data_pri_printed_2a473c_idx'), models.Index(fields=['vehicle', 'printed_at'], name='go_data_pri_vehicle_baa5e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='go_data_veh_vin_8c6770_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_reg'], name='go_data_veh_vehicle_1ac069_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['expiry_date'], name='go_data_veh_expiry__f7b9be_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='go_data_veh_vehicle_55d282_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['category'], name='go_data_veh_categor_091cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner'], name='go_data_veh_owner_i_7a2443_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='go_data_veh_is_acti_7413df_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at'], name='go_data_veh_created_c440f9_idx'),
        ),
    ]
